# Art Folder in dem die Resource-Dateien für die MariaDB-Datenbank in Kubernetes gespeichert werden.
apiVersion: v1
kind: Namespace
metadata:
  name: database-namespace
---
# PersistentVolumeClaim für die MariaDB-Datenbank, dass beim löschen des Pods die Daten nicht verloren gehen.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: database-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Weiterleitung des Ports 3306 der MariaDB-Datenbank auf den Port 10001 des lokalen Rechners, damit man über den lokalen Rechner auf die Datenbank zugreifen kann.
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database-namespace
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 3306
---
# Deployment für die MariaDB-Datenbank, die in einem Pod läuft. Das Deployment stellt sicher, dass immer die Anzahl an gewünschte Pods laufen. Der Pod wird mit einem PersistentVolumeClaim verbunden, um die Daten zu speichern.
# Ebenfalls werden Umgebungsvariablen für das Root-Passwort und den Datenbanknamen gesetzt.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.7.2-oraclelinux9
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "change-me"
            - name: MARIADB_DATABASE
              value: "test"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc